app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from app.main import bp
from app.main.utils import updateCart, getCartItems, getTotal
from flask import render_template, session, redirect, url_for, request, jsonify, abort, flash, current_app
from db import query_db, get_db, to_object
from datetime import timedelta, datetime
from werkzeug.security import generate_password_hash, check_password_hash

@bp.route('/')
def index():
    menu = query_db('''select menu.id, menu.name, category.name category,
                        price, description from menu join category
                        on menu.category = category.code
                        where is_special=1''')
    return render_template('main/index.html', title='Home', menu=menu)

@bp.route('/menu')
def menu():
    menu = query_db('''select menu.id, menu.name, category.name category,
                        price, description from menu join category
                        on menu.category = category.code''')
    return render_template('main/menu.html', title='Menu', menu=menu)

@bp.route('/cart')
def cart():
    items = getCartItems()
    return render_template('main/cart.html', title='Cart', items=items)

@bp.route('/addtocart/<int:id>/<int:qty>')
def addtoCart(id, qty):
    updateCart(id, qty)
    return redirect(request.referrer)

@bp.route('/remove/<int:id>')
def remove(id):
    cart = session.get('cart')
    if not cart: return abort(404)
    for i in cart:
        if str(i['id']) == str(id):
            cart.remove(i)
    session['cart'] = cart
    flash('Item removed from cart')
    return redirect(request.referrer)

@bp.route('/checkout')
def checkout():
    scheduled = session.get('scheduled')
    items = getCartItems()
    total = getTotal()
    if not items: abort(404)
    return render_template('main/checkout.html', title='Checkout', items=items, total=total, scheduled=scheduled)

@bp.route('/scheduled', methods=['GET', 'POST'])
def scheduled():
    min = datetime.today().strftime('%Y-%m-%d')
    max = (datetime.today() + timedelta(days=30)).strftime('%Y-%m-%d')

    if request.method == 'POST':
        date = request.form.get('date') # e.g. "2022-07-23"
        time = request.form.get('time') # e.g. "12:00"
        session['scheduled'] = {'date': date, 'time': time}
        return redirect(url_for('main.checkout'))
    return render_template('main/scheduled.html', title='Scheduled Order', min=min, max=max)

@bp.route('/payment', methods=['GET', 'POST'])
def payment():
    items = session.get('cart')
    if not items: abort(404)
    # make order, pop session scheduled and cart
    if request.method == 'POST':
        payment = request.form.get('payment')
        name = str(request.form.get('name')).title()
        email = request.form.get('email')
        phone = request.form.get('phone')
        phone = request.form.get('phone')
        note = request.form.get('note')
        next = int(query_db('select seq from sqlite_sequence where name="orders"', one=True)['seq']) + 1
        hash = generate_password_hash(current_app.config['SECRET_KEY'] + str(next))
        due = datetime.now()
        timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        if 'scheduled' in session:
            scheduled = session.get('scheduled')
            due = scheduled['date'] + ' ' + scheduled['time']
            due = datetime.strptime(due, "%Y-%m-%d %H:%M").strftime('%Y-%m-%d %H:%M:%S')

        query_db('insert into orders values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)',
        (None, name, email, phone, due, timestamp, note, payment, 0, hash, 1))
        for item in items:
            query_db('insert into order_items values (?, ?, ?)',
            (str(next), item['id'], item['qty']))
        get_db().commit()
        # send email
        session.pop('cart', None)
        session.pop('scheduled', None)
        flash('An order confirmation will be sent to your email.')
        return redirect(url_for('main.index'))
    return render_template('main/payment.html', title='Payment')

@bp.route('/lookup', methods=['GET', 'POST'])
def lookup():
    if request.method == 'POST':
        hash = request.form.get('hash')
        order = query_db('select * from orders where hash = ?', (hash,), one=True)
        if order:
            return redirect(url_for('main.order', hash=hash))
        else:
            abort(404)
    return render_template('main/lookup.html', title='Order Lookup')

@bp.route('/order/<hash>')
def order(hash):
    status = {"0": "Cancelled", "1": "Created", "2": "Preparing", "3": "Ready"}
    progress = {"0": "0", "1": "33", "2": "66", "3": "100"}
    order = query_db('select * from orders where hash = ?', (hash,), one=True)
    if not order: abort(401)

    items = query_db('''select * from order_items oi join menu m
                        on oi.item_id = m.id where oi.order_id = ?''',
                        (order['id'],))
    order = to_object(order)
    order['progress'] = progress[str(order['status'])]
    order['status'] = status[str(order['status'])]
    return render_template('main/order.html', title=f'Order #{order["id"]:02d}', order=order, items=items)

@bp.route('/contact')
def contact():
    return render_template('main/contact.html', title='Contact')

app/templates/main/cart.html
{% extends 'base.html' %}

{% block content %}
{% include 'main/cart_items.html' %}

{% if items %}
<a href="{{ url_for('main.checkout') }}"><button>Checkout</button></a>
<a href="{{ url_for('main.scheduled')}}"><button>Scheduled Order</button></a>
{% else %}
<a href="{{ url_for('main.menu') }}"><button>Menu</button></a>
{% endif %}
{% endblock %}

app/templates/main/cart_items.html
{% if items %}
{% for item in items %}
<div class="menu-item">
  <span>{{ item['name'] }}</span>
  <span>x{{ item['qty'] }}</span>
  <span>{{ "${:,.2f}".format(item['price'] * item['qty']) }}</span>
  <br><br>
  <input type="number" name="qty" id="qty-{{ item['id'] }}" value="{{ item['qty'] }}", min="1">
  <button onclick="addtoCart({{ item['id'] }})">Update</button>
  <button onclick="removefromCart({{ item['id'] }})">Remove</button>
</div>
{% endfor %}
{% else %}
<p>No items in cart.</p>
{% endif %}

app/templates/main/checkout.html
{% extends 'base.html' %}

{% block content %}
{% include 'main/checkout_items.html' %}
<a href="{{ url_for('main.cart') }}"><button>Back</button></a>
<a href="{{ url_for('main.payment') }}"><button>Payment</button></a>
{% endblock %}

app/templates/main/checkout_items.html
<div class="checkout-summary">
<h3>Checkout Summary</h3>
{% if scheduled %}
<p><i>Scheduled: {{scheduled['date']}} at {{scheduled['time']}}</i></p>
{% endif %}
<hr>
{% for item in items %}
  <p>
    <span>{{ item['name'] }}</span>
    <span>x{{ item['qty'] }}</span>
    <span>{{ "${:,.2f}".format(item['price'] * item['qty']) }}</span>
  </p>
{% endfor %}
<hr>
<p><b>Total Items: {{ items | sum(attribute='qty')}}</b></p>
<p><b>Total Price: {{ "${:,.2f}".format(total) }}</b></p>
</div>

app/templates/main/contact.html
{% extends 'base.html' %}

{% block content %}
<form method="post">
  <label for="name" required>Name</label>
  <input type="text" name="name">
  <label for="email" required>Email</label>
  <input type="email" name="email">
  <label for="phone">Phone</label>
  <input type="text" name="phone">
  <label for="message" required>Message</label>
  <textarea name="message" rows="3" cols="30"></textarea>

  <button>Submit</button>
</form>
{% endblock %}

app/templates/main/index.html
{% extends 'base.html' %}

{% block content %}
<h3>Today's Special</h3>
{% include 'main/menu_items.html' %}
{% endblock %}

app/templates/main/lookup.html
{% extends 'base.html' %}

{% block content %}
<form method="post">
  <input width="100" type="text" name="hash" placeholder="2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824">
  <button>Lookup</button>
</form>
{% endblock %}

app/templates/main/menu.html
{% extends 'base.html' %}

{% block content %}
{% include 'main/menu_items.html' %}
{% endblock %}

app/templates/main/menu_items.html
{% for item in menu %}
<div class="menu-item">
  <h4>{{ item['name'] }}</h4>
  <p>{{ item['category'] }}</p>
  <p>{{ item['description'] }}</p>
  <p>{{ "${:,.2f}".format(item['price']) }}</p>
  <img src="https://picsum.photos/seed/{{ loop.index }}/200"><br>
  <label for="qty">Qty</label>
  <input type="number" name="qty" id="qty-{{ item['id'] }}" value="1", min="1">
  <button onclick="addtoCart({{ item['id'] }})">Add to Cart</button>
</div>
{% endfor %}

app/templates/main/order.html
{% extends 'base.html' %}

{% block content %}
<label for="progress">Order Status: {{ order['status'] }} ({{ order['progress'] }}%)</label><br>
<progress name="progress" value="{{ order['progress'] }}" max="100"></progress>
<hr>
<h3>Items</h3>
{% for item in items %}
<p>{{ item['name'] }} x{{ item['qty']|int }}</p>
{% endfor %}
<hr>
{% if order['status'] == "Created" %}
<button onclick="alert('Please call +1 (314) 345 0652 for support.')">Contact</button>
{% elif order['status'] == "Ready" %}
<p><b>Your order is ready for pickup!</b></p>
{% endif %}

{% endblock %}

app/templates/main/payment.html
{% extends 'base.html' %}

{% block content %}
<form method="post">
  <label for="name">Name</label>
  <input type="text" name="name">
  <label for="email">Email</label>
  <input type="email" name="email">
  <label for="phone">Phone</label>
  <input type="tel" name="phone">
  <label for="note" required>Note</label>
  <textarea name="note" rows="3" cols="30" placeholder="optional"></textarea>

  <select name="payment" id="payment" onchange="showBadge()" required>
    <option value="cash">Cash</option>
    <option value="zelle">Zelle</option>
  </select>
  <button>Order</button>
</form>
<div id="zelle">
</div>
{% endblock %}

{% block scripts %}
<script>
  function showBadge() {
    const root = document.getElementById('zelle');
    if (document.getElementById('payment').value == 'zelle') {
      badges = [
                m('img', {width: "40%", style: "float: left; border: 1px solid; border-radius: 5%;", src: "{{ url_for('static', filename='zelle_email.jpg') }}"}),
                m('img', {width: "40%", style: "margin-left: 5%; float: left;", src: "{{ url_for('static', filename='zelle_phone.jpg') }}"})
              ]
      m.render(root, badges)
    }
    else {
      m.render(root, null)
    }
  };
</script>
{% endblock %}

app/templates/main/scheduled.html
{% extends 'base.html' %}

{% block content %}
<form method="post">
  <label for="date">Date</label>
  <input type="date" name="date" min="{{ min }}" max="{{ max }}" value="{{ min }}">
  <label for="time" required>Time</label>
  <input type="time" name="time" min="09:00" max="17:00" value="12:00" required>
  <a href="{{ url_for('main.payment') }}"><button>Checkout</button></a>
</form>
{% endblock %}